name: magictune
workers:
- name: worker
  github:
    repo: rattrap/magictune
    branch: master
    deploy_on_push: true
  dockerfile_path: Dockerfile.cron
  envs:
    - key: KRAKEN_KEY
      scope: RUN_TIME
      value: KRAKEN_KEY
    - key: KRAKEN_SECRET
      scope: RUN_TIME
      value: KRAKEN_SECRET
    - key: DRY_RUN
      scope: RUN_TIME
      value: true
    - key: HIDE_LOW_VOLUME
      scope: RUN_TIME
      value: false
    - key: CRON_INTERVAL
      scope: RUN_TIME
      value: '*/6 * * * *'